version:            '2'
services:
  data:
    
  cc:
    container_name:
      "cc"
    build:
      context:      ./cc
    image:
      "cc"
    ports:
      - "3000:3000"
    depends_on:
      - data
    restart:        unless-stopped
  mi:
    container_name:
      "mi"
    build:
      context:      ./mi
    image:
      "mi"
    ports:
      - "3001:3001"
    depends_on:
      - data
    restart:        unless-stopped
  mc:
    container_name:
      "mc"
    build:
      context:      ./mc
    image:
      "mc"
    ports:
      - "3003:3003"
    depends_on:
      - data
    restart:        unless-stopped
  client:
    container_name:
      "client"
    build:
      context:      ./client/v.0
    image:
      "client"
    command:        ng serve --host 0.0.0.0 --public 127.0.0.1:80
    ports:
      - "80:80"
    restart:        unless-stopped
